### ISSUE TITLE
Calendar loading indefinitely after upgrade

### ISSUE THREAD

**Issue by suamikim** [owncloud/calendar#498]
Hi,

I've just updated from 8.2.3 to 9.0.1 and mostly it seems to be running just fine so far.

I had to activate all of my calendars manually one by one by clicking on the calendar name in the list at the left. This worked for all except one. The one in question indefinitely shows the loading icon.

![capture](https://cloud.githubusercontent.com/assets/2870365/14911366/38a8ab24-0df5-11e6-8c2f-450fbf6de06e.PNG)

I don't find any associated entries in the logs.

Also I can export the calendar as a ICS file which I can open without any trouble e.g. in MS Outlook. Deleting the calendar in ownCloud and importing the exported file leads to the same state as before (indefinite loading icon).

I already tried to migrate the calendars manually with the command `sudo -u www-data php occ dav:migrate-calendars [user]` which finished without any errors but didn't solve the problem.

Afterwards I've checked the counts in the old & new calendar tables as described [here](http://morrisjobke.de/2016/03/07/ownCloud-9.0-calendar-migration-analysis/).

The counts are the same in both tables except, that the calendar in question is listed twice in the new table since I've deleted & reimported it:

![calendar_migration](https://cloud.githubusercontent.com/assets/2870365/14911414/8241e57a-0df5-11e6-814e-aba397e486f1.png)
Removed names of other calendars for privacy reasons...

I'd really appreciate any help with this!

Ps.: I've already posted this question in the [ownCloud forums](https://forum.owncloud.org/viewtopic.php?f=38&t=36309)

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md)

**Comment by albatros69** [comment]
I've been bitten by the same issue (described in #496).
By the way, even for the period that sometimes works, the events are shifted one day in the past.

**Comment by georgehrke** [comment]
Without logs I can't tell if its the same issue @albatros69 has ;)

**Comment by suamikim** [comment]
### Steps to reproduce

Don't know...

### Expected behaviour

All calendars should show the colored icon in the list at the right after their activation.

### Actual behaviour

One calendar shows a loading icon which doesn't disappear and the calendars entries are not shown at all:
![38a8ab24-0df5-11e6-8c2f-450fbf6de06e](https://cloud.githubusercontent.com/assets/2870365/14914700/e50b143a-0e0c-11e6-8fdc-463d7ce06110.PNG)

### Server configuration

**Operating system**: Linux Mint 17.1 Rebecca (GNU/Linux 3.13.0-37-generic x86_64)

**Web server:**  Apache/2.4.20 (Ubuntu)

**Database:** MariaDB

**PHP version:** PHP 5.6.20

**ownCloud version:** 9.0.1 stable

**Updated from an older ownCloud or fresh install:** Updated from 8.2.3

**Where did you install ownCloud from:** Tar from website

**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.1
  - comments: 0.2
  - contacts: 1.2.0.0
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - news: 8.7.1
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocxqlr7g3ae0",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "some.more.domains.com"
        ],
        "datadirectory": "\/home\/mike\/owncloud",
        "overwrite.cli.url": "https:\/\/localhost\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.1.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "michael",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "tls",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "maintenance": false,
        "theme": "",
        "trashbin_retention_obligation": "auto",
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration

**Browser:** Firefox 45, Chrome 49, Chrome 50, ...

**Operating system:** Windows 10

### Logs

#### Web server error log

All apache logs during the time I did the following:
*Reload calendar page
*Deactivate calendar in question (lumi)
*Activate calendar in question (lumi)

```
access.log

::1 - - [29/Apr/2016:14:39:02 +0200] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.20 (Ubuntu) PHP/5.6.20-1+deb.sury.org~trusty+1 OpenSSL/1.0.2g (internal dummy connection)"
::1 - - [29/Apr/2016:14:39:11 +0200] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.20 (Ubuntu) PHP/5.6.20-1+deb.sury.org~trusty+1 OpenSSL/1.0.2g (internal dummy connection)"

I can't find no error logs in this time...
```

#### ownCloud log (data/owncloud.log)

[owncloud.log.txt](https://github.com/owncloud/calendar/files/242461/owncloud.log.txt)

#### Browser log

![js_log](https://cloud.githubusercontent.com/assets/2870365/14916447/0b5e8394-0e1a-11e6-874c-c001afcbef49.PNG)

**Comment by georgehrke** [comment]
So there seems to be one event with a certain recurrence rule that kills our calendar data parser.
I'll prepare a patch so you can easily extract that certain event.

**Comment by menaceone** [comment]
Same problem here.
One of my calendars loads infinitely since upgrade to latest calendar 1.1.

Browser log **without** broken calendar:
![console_without_borken_calendar](https://cloud.githubusercontent.com/assets/7307507/14942618/6d272bb8-0fc2-11e6-87c5-26af144b89b3.png)

Browser log **with** broken calendar:
![console_with_borken_calendar](https://cloud.githubusercontent.com/assets/7307507/14942623/832dff9a-0fc2-11e6-8638-50283912fc5a.png)

"TypeError: dt.convertToZone is not a function" seems to be a trace to the problem.

**Comment by caTenschert** [comment]
same probleme after upgrading to 9.0.1.
calender 1.1.
error message in browser
#####
app.js?v=3a9d458…:3037 Uncaught (in promise) TypeError: dt.convertToZone is not a function(…)convertTimezoneIfNecessary @ app.js?v=3a9d458…:3037getTime @ app.js?v=3a9d458…:3097(anonymous function) @ app.js?v=3a9d458…:3178forEach @ angular.js?v=3a9d458…:321VEvent.getFcEvent @ app.js?v=3a9d458…:3167(anonymous function) @ app.js?v=3a9d458…:2085
######

upgrade to 9.0.2 still allive
getting kalender from android smartphone with caldav, no error shown.
